### ISSUE TITLE
edit page for plans

### ISSUE THREAD

**Issue by felixangell** [HandsFree/teacherui-frontend#7]
#### Issue
There isn't a way to edit a GLP's description, domain, topic.. etc. from the UI. This can be done from within the authoring tool, but most teachers would prefer a simple form to edit the GLP.

Editing the available times of GLP could be done here too.

The edit page could contain the link to the authoring tool for further editing

#### TODO
- [x] Change Edit option to open page with form where the glp can be edited
- [ ] GLP available times must be editable
- [x] Link to AT
- [ ] Add Edit buttons inside the view GLP page
- [x] Delete Plan Button
- [ ] Change Name, Topic, Domain, Category, Description, LO’s, Competences, Age, Year
- [x] Change between public/private
- [ ] Edit Files uploaded to GLP
- [ ] Changing assigned groups and students
- [ ] If a plan is not owned by the teacher, check read-only flag. If read-only, show the plan is immutable and offer opening in AT or clone
